version: '3'

services:
  shop:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3636:3306
    expose:
      - '3636'
    volumes:
      - /data/mysql
  kotlin-demo-app:
    image: kotlin-demo-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - shop
    ports:
      - 8080:8080
    expose:
      - '8080'
    volumes:
      - /data/kotlin-demo-app